markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks

collections:
  authors:
    output: true
  photos:
    output: true
  subjects:
    output: true

defaults:
  - scope:
      path: ""
      type: "photos"
    values:
      layout: "photo"
  - scope:
      path: ""
      type: "subjects"
    values:
      layout: "subject"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
