markdown: kramdown
highlighter: rouge
sass:
  style: compressed
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks

collections:
  collections:
    output: true

defaults:
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "collection"
  - scope:
      path: ""
    values:
      layout: "default"
