collections:
  authors:
    output: true
  photos:
    output: true
  topphotos:
    output: true

defaults:
  - scope:
      path: ""
      type: "photos"
    values:
      layout: "photo"
  - scope:
      path: ""
      type: "topphotos"
    values:
      layout: "photo"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
